userAgent: Mozilla/5.0 (Windows; U; WindowsNT 5.1; en-US; rv1.8.1.6) Gecko/20070725 Firefox/2.0.0.6

sources:
  hardmob:
    url: http://www.hardmob.com.br/promocoes/
    elements:
      title: title
